import Service from '@ember/service';

/**
 * Inject session service to an Ember Object
 * @param {Object} self - Ember object generated by ember-qunit moduleFor()
 */
export default function injectSessionStub(self) {
  const sessionStub = Service.extend({
    isAuthenticated() {
      return true;
    }
  });

  self.owner.register('service:session', sessionStub);
}
